name = "palki-sahib-video-creator-trigger"
main = "src/index.js"
compatibility_date = "2026-07-29"

[[kv_namespaces]]
binding = "RUN_STATUS_KV"
id = "GURBANI_KV"

[triggers]
crons = [
    "0,30 23,0-1 * * *",
]
